In [1]:
library("eurostat")

In [3]:
get_eurostat("ilc_peps01")

Table ilc_peps01 cached at /tmp/RtmpUnfhHw/eurostat/ilc_peps01_date_code_TF.rds

      unit    age    sex geo time       values
1     PC      TOTAL  F   AT  2017-01-01 19.3
2     PC      TOTAL  F   BE  2017-01-01 21.4
3     PC      TOTAL  F   BG  2017-01-01 40.4
4     PC      TOTAL  F   CZ  2017-01-01 13.9
5     PC      TOTAL  F   DK  2017-01-01 16.6
6     PC      TOTAL  F   EE  2017-01-01 25.6
7     PC      TOTAL  F   EL  2017-01-01 35.7
8     PC      TOTAL  F   ES  2017-01-01 27.1
9     PC      TOTAL  F   FI  2017-01-01 15.7
10    PC      TOTAL  F   HU  2017-01-01 26.1
11    PC      TOTAL  F   LV  2017-01-01 31.1
12    PC      TOTAL  F   MT  2017-01-01 20.1
13    PC      TOTAL  F   NL  2017-01-01 17.3
14    PC      TOTAL  F   NO  2017-01-01 17.0
15    PC      TOTAL  F   PL  2017-01-01 19.6
16    PC      TOTAL  F   PT  2017-01-01 24.0
17    PC      TOTAL  F   RO  2017-01-01 36.5
18    PC      TOTAL  F   SI  2017-01-01 18.3
19    PC      TOTAL  M   AT  2017-01-01 16.8
20    PC      TOTAL  M   BE  2017-01-01 19.1
21    PC      TOTAL  M   BG  2017-01-01 37.2
22    PC      TOTAL  M   CZ  2017-01-01 10.5
23    PC      TOTAL  M   DK  2017-01-01 17.8
24    PC      TOTAL  M   EE  2017-01-01 21.0
25    PC      TOTAL  M   EL  2017-01-01 33.9
26    PC      TOTAL  M   ES  2017-01-01 26.0
27    PC      TOTAL  M   FI  2017-01-01 15.6
28    PC      TOTAL  M   HU  2017-01-01 25.0
29    PC      TOTAL  M   LV  2017-01-01 24.9
30    PC      TOTAL  M   MT  2017-01-01 18.3
⋮     ⋮       ⋮      ⋮   ⋮   ⋮          ⋮
98755 THS_PER Y_LT65 M   LU  2003-01-01   28
98756 THS_PER Y_LT65 M   NO  2003-01-01  220
98757 THS_PER Y_LT65 T   AT  2003-01-01 1029
98758 THS_PER Y_LT65 T   BE  2003-01-01 2003
98759 THS_PER Y_LT65 T   DK  2003-01-01  735
98760 THS_PER Y_LT65 T   EL  2003-01-01 2675
98761 THS_PER Y_LT65 T   IE  2003-01-01  795
98762 THS_PER Y_LT65 T   LU  2003-01-01   63
98763 THS_PER Y_LT65 T   NO  2003-01-01  451
98764 THS_PER Y_LT75 F   AT  2003-01-01  587
98765 THS_PER Y_LT75 F   BE  2003-01-01 1190
98766 THS_PER Y_LT75 F   DK  2003-01-01  418
98767 THS_PER Y_LT75 F   EL  2003-01-01 1660
98768 THS_PER Y_LT75 F   IE  2003-01-01  447
98769 THS_PER Y_LT75 F   LU  2003-01-01   38
98770 THS_PER Y_LT75 F   NO  2003-01-01  263
98771 THS_PER Y_LT75 M   AT  2003-01-01  550
98772 THS_PER Y_LT75 M   BE  2003-01-01 1034
98773 THS_PER Y_LT75 M   DK  2003-01-01  384
98774 THS_PER Y_LT75 M   EL  2003-01-01 1469
98775 THS_PER Y_LT75 M   IE  2003-01-01  428
98776 THS_PER Y_LT75 M   LU  2003-01-01   29
98777 THS_PER Y_LT75 M   NO  2003-01-01  233
98778 THS_PER Y_LT75 T   AT  2003-01-01 1137
98779 THS_PER Y_LT75 T   BE  2003-01-01 2224
98780 THS_PER Y_LT75 T   DK  2003-01-01  802
98781 THS_PER Y_LT75 T   EL  2003-01-01 3129
98782 THS_PER Y_LT75 T   IE  2003-01-01  875
98783 THS_PER Y_LT75 T   LU  2003-01-01   67
98784 THS_PER Y_LT75 T   NO  2003-01-01  496